language: c
sudo: required
install:
  - wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-ocaml.sh
  - bash -ex .travis-ocaml.sh
  - eval `opam config env`
  - opam install -y menhir ounit
script:
  - ./run-test.sh
env:
  - OCAML_VERSION=4.06
